export default function SecurityContent() {
  return (
    <div className="user-view__content">
      <div className="user-view__back-link"></div>
      <div className="user-view__form-container">
        <h2 className="heading-secondary ma-bt-md undefined">
          Two-Factor Authentication
        </h2>
        <p className="title__description">
          Protect your account with an extra layer of security by requiring a
          code generated by your smartphone in addition to your password. This
          is relevant only if you log in with an email and password. It is not
          relevant for 3rd-party logins.
        </p>
        <div className="form__group right ma-bt-md">
          <button type="button" className="btn btn--large btn--green false">
            Setup two factor
          </button>
        </div>
        <p className="title__description ma-t-lg">
          * User need email to be verified to setup 2FA
        </p>
      </div>
      <div className="line">&nbsp;</div>
      <div className="user-view__form-container">
        <h2 className="heading-secondary ma-bt-md undefined">
          Deactivate or delete account
        </h2>
        <div>
          <div className="input-radio-container">
            <input
              id="deactivate"
              type="radio"
              name="activity"
              value="deactivate"
              checked
            />
            <label htmlFor="deactivate">
              <p>
                <strong>Deactivate Account:</strong> Deactivating your account
                is <strong>temporary</strong>. Your account will be disabled and
                will not be visible to other users. Your data will not be
                deleted. You can reactiavte your acount simply by login.
              </p>
            </label>
          </div>
          <div className="input-radio-container">
            <input id="delete" type="radio" name="activity" value="delete" />
            <label htmlFor="delete">
              <p>
                <strong>Delete Account:</strong> Deleting your account is{" "}
                <strong>permanent</strong>. All your data (bookings, reviews and
                feedbacks) will be removed and you will not be able to retrieve
                your account anymore.
              </p>
            </label>
          </div>
        </div>
        <div className="form__group right">
          <button type="submit" className="btn btn--large btn--red">
            deactivate
          </button>
        </div>
      </div>
    </div>
  );
}
